blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/webpack/webpack/discussions/new?category=ideas
    about: Request new features or suggest improvements
  - name: Ask for Help
    url: https://github.com/webpack/webpack/discussions/new?category=q-a
    about: Ask questions and get help from the community
